# Generated by Django 5.0.6 on 2026-08-06 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_level', models.CharField(max_length=20)),
                ('image_data', models.BinaryField()),
                ('content_type', models.CharField(max_length=30)),
                ('width_px', models.PositiveIntegerField()),
                ('height_px', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='core.place')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('place', 'floor_level')},
            },
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('waypoint_type', models.CharField(choices=[('entrance', 'Entrance'), ('elevator', 'Elevator'), ('ramp', 'Ramp'), ('stairs', 'Stairs'), ('junction', 'Junction'), ('facility', 'Facility')], max_length=20)),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('qr_code_value', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('floor_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='core.floorplan')),
                ('linked_access_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waypoints', to='core.accesspoint')),
                ('linked_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waypoints', to='core.facility')),
            ],
        ),
        migrations.CreateModel(
            name='WaypointEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_meters', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('path_type', models.CharField(choices=[('corridor', 'Corridor'), ('ramp', 'Ramp'), ('stairs', 'Stairs'), ('elevator_shaft', 'Elevator (between floors)')], default='corridor', max_length=20)),
                ('is_accessible', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('floor_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='core.floorplan')),
                ('from_waypoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_from', to='core.waypoint')),
                ('to_waypoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_to', to='core.waypoint')),
            ],
        ),
    ]
