# Generated by Django 5.0.6 on 2026-08-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_floorplan_waypoint_waypointedge'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
