# Generated by Django 5.0.6 on 2026-08-27 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_place_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerticalConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('elevator', 'Elevator'), ('stairs', 'Stairs'), ('ramp', 'Ramp')], max_length=20)),
                ('distance_meters', models.DecimalField(decimal_places=2, default=5, max_digits=6)),
                ('is_accessible', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('from_waypoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vertical_edges_from', to='core.waypoint')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vertical_connections', to='core.place')),
                ('to_waypoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vertical_edges_to', to='core.waypoint')),
            ],
        ),
    ]
